server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hanh?useSSL=false
    username: root
    password: Lekhachanh123@gmail.com
    hikari:
      max-lifetime: 600000
      maximum-pool-size: 2
      connection-test-query: select 1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
logging:
  level: debug
